// Re-exportar apenas os serviços (classes), não os tipos para evitar conflitos de nomes duplicados
export { PersonService, personService } from './personService'
export { ScheduledAbsenceService, scheduledAbsenceService } from './scheduledAbsenceService'
export { AbsenceTypeService, absenceTypeService } from './absenceTypeService'
export { ScheduledAreaService, scheduledAreaService } from './scheduledAreaService'
export { ResponsibilityService, responsibilityService } from './responsibilityService'
export { PersonAreaService, personAreaService } from './personAreaService'
export { GroupService, groupService } from './groupService'
export { GroupMemberService, groupMemberService } from './groupMemberService'
export { TeamService, teamService } from './teamService'
export { ScheduleGenerationService, scheduleGenerationService } from './scheduleGenerationService'
export { ScheduleService, scheduleService } from './scheduleService'
export { ScheduleMemberService, scheduleMemberService } from './scheduleMemberService'
export { ScheduleCommentService, scheduleCommentService } from './scheduleCommentService'

